; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial monitor
monitor_speed = 115200

; Uncomment and set if auto-detection picks the wrong port
; upload_port = COM3
; monitor_port = COM3

lib_deps =
    ; add libraries here as areas need them, e.g.:
    ; madhephaestus/ESP32Servo @ ^3.0.5

build_flags =
    -D CORE_DEBUG_LEVEL=3
